# linear_regression_config.yaml
data:
  path: 'data/dataset.csv'
  preprocessing:
    fill_missing_values: true
    categorical_encoding: 'one_hot'
    normalization: true
    train_test_split_ratio: 0.8

model:
  params:
    learning_rate: 0.01
    regularization: 'L2'
    regularization_rate: 0.1
    batch_size: 32
    early_stopping: true
    early_stopping_patience: 10
  save_path: 'models/linear_regressor_{timestamp}.pkl'

# Model Parameters
model:
  learning_rate: 0.01
  num_iterations: 1000

# Feature Scaling Configuration
scaler:
  method: StandardScaler
  with_bias: true

# Data Split Configuration
data_split:
  test_size: 0.2
  random_state: 42

# Evaluation Metrics Configuration
metrics:
  - mean_squared_error
  - r2_score
